site_name: JunkRats Wiki
site_description: Official JunkRats lore and documentation
site_author: Not-So Classic Games
site_url: https://junkratswiki.notsoclassicgames.com
copyright: © Not-So Classic Games

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: slate
      primary: black

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

extra:
  generator: false

plugins:
  - search
  - autorefs
  - roamlinks
  - awesome-pages
  - git-revision-date-localized
  - macros:
      module_name: main